version: '3.8'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./metrics/grafana:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./:/test
    working_dir: "/test"
    entrypoint: ["k6", "run",  "test/load.test.js", "-e", "BASE_URL=http://json-server:3000"]

  json-server:
    image: my/json-server:latest
    hostname: json-server
    container_name: json-server
    build:
      context: .
      dockerfile: json_server/Dockerfile
    ports:
      - "3001:3000"
    networks:
      - k6
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
        reservations:
          cpus: '0.5'
          memory: 150M
