version: '3.8'

networks:
  k6:
  grafana:

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./metrics/grafana:/etc/grafana/provisioning/

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./:/test
    working_dir: "/test"
    entrypoint: ["k6", "run",  "test/load.test.js", "-e", "BASE_URL=http://json-server:3000", "--address", "0.0.0.0:6565"]

  json-server:
    image: savvagenchevskiy/json-server:latest
    container_name: json-server
    build:
      context: .
      dockerfile: json_server/Dockerfile
    ports:
      - "3001:3000"
    networks:
      - k6
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
        reservations:
          cpus: '0.5'
          memory: 150M
  
  # Gathering metrics with prometheus and k6_exporter

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    networks: 
      - k6
      - grafana

  k6_exporter:
    image: savvagenchevskiy/k6-exporter:latest
    container_name: k6_exporter
    networks: 
      - k6
    #network_mode: host
    ports:
      - 9091:9091
    environment:
      - METRICS_PORT=9091
      - COLLECT_INTERVAL=10
      - K6_SERVER=http://k6:6565
    depends_on: 
      - k6