version: "3.5"
services:
  json-server:
    image: my/json-server:latest
    hostname: json-server
    container_name: json-server
    ports:
      - "3000:3000"
    networks:
      - performance
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
        reservations:
          cpus: '0.5'
          memory: 150M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s

networks:
  performance:
    driver: bridge